### ISSUE TITLE
Use convo name instead of participant list

### ISSUE THREAD

**Issue by algesten** [algesten/yakayak#2]
Gets a bit silly with many.

![screen shot 2015-05-29 at 10 03 35](https://cloud.githubusercontent.com/assets/227204/7877989/7ccd1204-05ea-11e5-9bae-204c5a47a097.png)

**Comment by davibe** [comment]
I think this conversation had people that are not in your "circles"
w

**Comment by algesten** [comment]
oh yes. i don't use circles much.
